### ISSUE TITLE
Perl utils cannot be found when running the pipeline outside of the user home directory

### ISSUE THREAD

**Issue by JamalEH** [guigolab/ipsa-nf#4]
Dear,

Thank you for sharing and making publicly available the great tool IPSA.

While running the test pipeline with the following command: 
./nextflow run guigolab/ipsa-nf

I got the following error:
exit status : 2
Error report: Error executing process > 'annotate (E14_rep1.A03.ssj)'

Caused by:
  Process `annotate (E14_rep1.A03.ssj)` terminated with an error exit status (2)

Command executed:

  annotate.pl -annot annotation.gfx -dbx genome.dbx -idx genome.idx -deltaSS 10 -in E14_rep1.A02.ssj.tsv > E14_rep1.A03.ssj.tsv

Command exit status:
  2

Command output:
  (empty)

Command error:
  Can't locate Perl/utils.pm in @INC (you may need to install the Perl::utils module) (@INC contains: /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.
  BEGIN failed--compilation aborted at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.

Work dir:
  /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/98/a1b7a3951b7f892b36677c61b4337b

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
WARN: Killing pending tasks (3)
ERROR ~ Error executing process > 'annotate (E14_rep1.A03.ssj)'

Caused by:
  Process `annotate (E14_rep1.A03.ssj)` terminated with an error exit status (2)

Command executed:

  annotate.pl -annot annotation.gfx -dbx genome.dbx -idx genome.idx -deltaSS 10 -in E14_rep1.A02.ssj.tsv > E14_rep1.A03.ssj.tsv

Command exit status:
  2

Command output:
  (empty)

Command error:
  Can't locate Perl/utils.pm in @INC (you may need to install the Perl::utils module) (@INC contains: /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.
  BEGIN failed--compilation aborted at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.

Work dir:
  /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/98/a1b7a3951b7f892b36677c61b4337b

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details

I checked the location of the utils.pm file and it's located at :
/home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/Perl/utils.pm

I think that the problem is related to the location of the utils.pm file at the annotate process step. Could you please help me to fix this bug?
Thank you so much in advance!
Best regards,
Jamal.

**Comment by emi80** [comment]
Hi @JamalEH, apologies for the late feedback on this.

The problem looks weird as the location of perl modules is specified in the [main configuration file](https://github.com/guigolab/ipsa-nf/blob/master/nextflow.config#L11) and loaded automatically  by nextflow. I made a test run on my machine and the pipeline completed successfully.

Can you please give it another try and let me know? Did you add any additional configuration option to the run?

Best

**Comment by JamalEH** [comment]
Hi dear,
Thank you so much for your reply!

I gave another try to run the pipeline test script "./nextflow run guigolab/ipsa-nf" from within the IPSA directory and I still get the same error. I did not add any other configuration option to the run. All what I did is the following:
1. curl -fsSL get.nextflow.io | bash : To install the pipeline.
2. docker pull guigolab/ipsa-nf@sha256:29750072f2b42ee8ea094a331f53bc5906183591a71ed26619ea76b12b6be3ed
3. ./nextflow run guigolab/ipsa-nf : to test the pipeline

Bests,
Jamal.

**Comment by emi80** [comment]
Could you please do the following?

- move to the failing annotate task directory (e.g. `/vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/98/a1b7a3951b7f892b36677c61b4337b`)
- edit `.command.sh` and put an `env` command on the line before the `annotate.pl ...` command
- run  `bash .command.run` from the terminal
- paste the content of `.command.out` in a comment in this issue

Thanks

**Comment by JamalEH** [comment]
all  what I have in the failing directory is symbolic links to data file. There is no file called .command.sh in that directory.

Herewith the content of the directory:
annotation.gfx -> /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/34/a88a388aaecb50251d6a873b94a3d5/annotation.gfx
lrwxrwxrwx 1 jelhasnaoui jelhasnaoui 138 Jul 19 15:21 E14_rep2.A02.ssj.tsv -> /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/11/0a98ebb71a16f4cb42cc8361cf4d37/E14_rep2.A02.ssj.tsv
-rw-r--r-- 1 root        root          0 Jul 19 15:21 E14_rep2.A03.ssj.tsv
lrwxrwxrwx 1 jelhasnaoui jelhasnaoui 128 Jul 19 15:21 genome.dbx -> /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/3b/d2a1160630be6cc85d22aeab310bae/genome.dbx
lrwxrwxrwx 1 jelhasnaoui jelhasnaoui 128 Jul 19 15:21 genome.idx -> /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/3b/d2a1160630be6cc85d22aeab310bae/genome.idx

As I'm working from a server, for which I'm not a sudouser, there maybe a problem in calling the "Perl::utils" module, since the error specifies that the error is caused by line 2 in annotate.pl file which contains "Perl::utils"? or could it be due to using a prior version of Perl?

Thank you and I apologize for this inconvenient issue!

**Comment by emi80** [comment]
It's an hidden file you should be able to see it with `ls -al`

**Comment by emi80** [comment]
There is no need to have sudo permissions. The errors says:

```
an't locate Perl/utils.pm in @inc (you may need to install the Perl::utils module) (@inc contains: /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl 
```

But `@inc` contains `/home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf` which is where the `Perl/utils.pm` is and everything should be run inside a container so the Perl version should not matter.

**Comment by JamalEH** [comment]
Sorry, 

After adding env to the second line in the .command.sh file Herewith the content of .command.out after runing .command.run:
HOSTNAME=bdaeb9e04699
PERL5LIB=/home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf
PATH=/home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/maptools-3.2/bin:/sjcount-3.1:/sjcount-3.1/samtools-0.1.18
_=/usr/bin/env
PWD=/vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/87/a4ee60f02f73db27d9c3d187c9f4b7
HOME=/root
SHLVL=2

and on the terminal, running the .command.run command prints the following:
HOSTNAME=bdaeb9e04699
PERL5LIB=/home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf
PATH=/home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/maptools-3.2/bin:/sjcount-3.1:/sjcount-3.1/samtools-0.1.18
_=/usr/bin/env
PWD=/vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/87/a4ee60f02f73db27d9c3d187c9f4b7
HOME=/root
SHLVL=2
Can't locate Perl/utils.pm in @INC (you may need to install the Perl::utils module) (@INC contains: /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.
BEGIN failed--compilation aborted at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.

Thanks!

**Comment by emi80** [comment]
Ok, I found the problem. It should be fixed now. The pipeline folder was not automatically mounted by Nextflow if you run the pipeline in a folder that is not within your home directory.

Can you please try now and let me know? You will need to update `ipsa-nf` code base with:
```
nextflow pull guigolab/ipsa-nf
```

**Comment by JamalEH** [comment]
Hi dear,
Thank you so much for your help and your valuable time!

When I work from a folder located in my home directory, the pipeline just runs successfully! But instead, if the wd folder is not directly located on my home directory, I still get always the same error, even after running nextflow pull guigolab/grape-nf.
_### N E X T F L O W  ~  version 19.04.1
Launching `guigolab/ipsa-nf` [cranky_tesla] - revision: a0321a0914 [master]
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [d0336118f0]

I P S A ~ Integrative Pipeline for Splicing Analyses

General parameters
------------------
Index file                         : /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/data/index.tsv
Genome                             : /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/data/genome.fa
Annotation                         : /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/data/annotation.gtf
Merge output name                  : all
Merged features                    : cosi, cosi3, cosi5, cosit, psi, psi3, psi5, psit, exc, inc, ret
Output dir                         : data
Sjcount parameters                 : -
Include microexons                 : false

Thresholds and limits
---------------------
Margin for aggregate               : 5
Minimum counts for denominator     : 10
Splice sites distance threshold    : 10
Entropy lowewr threshold           : 1.5
Annotation status lower threshold  : 0

[warm up] executor > local
executor >  local (22)
[06/0ce558] process > preprocBams  [100%] 4 of 4 ✔
executor >  local (22)
[06/0ce558] process > preprocBams  [100%] 4 of 4 ✔
[a2/e918b1] process > txElements   [100%] 1 of 1 ✔
[4a/a8b8ce] process > genomeIndex  [100%] 1 of 1 ✔
[35/091714] process > sjcount      [100%] 4 of 4 ✔
[99/384e3c] process > aggregateSSJ [100%] 4 of 4 ✔
[25/54e500] process > aggregateSSC [100%] 4 of 4 ✔
[f7/214220] process > annotate     [100%] 4 of 4, failed: 4
Pipeline execution summary
---------------------------
Completed at: Fri Jul 19 17:12:33 CEST 2019
Duration    : 22.4s
Success     : false
workDir     : /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work
exit status : 2
Error report: Error executing process > 'annotate (E14_rep1.A03.ssj)'

Caused by:
  Process `annotate (E14_rep1.A03.ssj)` terminated with an error exit status (2)

Command executed:

  annotate.pl -annot annotation.gfx -dbx genome.dbx -idx genome.idx -deltaSS 10 -in E14_rep1.A02.ssj.tsv > E14_rep1.A03.ssj.tsv

Command exit status:
  2

Command output:
  (empty)

Command error:
  Can't locate Perl/utils.pm in @INC (you may need to install the Perl::utils module) (@INC contains: /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.
  BEGIN failed--compilation aborted at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.

Work dir:
  /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/2f/9b1adb5a0c383b8853cfff21936145

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
WARN: Killing pending tasks (3)
ERROR ~ Error executing process > 'annotate (E14_rep1.A03.ssj)'

Caused by:
  Process `annotate (E14_rep1.A03.ssj)` terminated with an error exit status (2)

Command executed:

  annotate.pl -annot annotation.gfx -dbx genome.dbx -idx genome.idx -deltaSS 10 -in E14_rep1.A02.ssj.tsv > E14_rep1.A03.ssj.tsv

Command exit status:
  2

Command output:
  (empty)

Command error:
  Can't locate Perl/utils.pm in @INC (you may need to install the Perl::utils module) (@INC contains: /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.
  BEGIN failed--compilation aborted at /home/jelhasnaoui/.nextflow/assets/guigolab/ipsa-nf/bin/annotate.pl line 2.

Work dir:
  /vol3/Reference/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/pipelines/IPSA/work/2f/9b1adb5a0c383b8853cfff21936145

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details_

Thank you again,
Best regards,
Jamal.

**Comment by emi80** [comment]
You did not pull the new revision. Please run:

nextflow pull guigolab/ipsa-nf

**Comment by JamalEH** [comment]
Runing "nextflow pull guigolab/ipsa-nf" not "nextflow pull gugolab/grape-nf" solved the problem.

Thanks!
Best regards,
Jamal.

**Comment by emi80** [comment]
Sorry, my bad. Thanks for reporting this. I'll close it now.
